// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCv2Bm6cMCO66NiuuNexPopBW6JGSbPTw',
    appId: '1:61665813587:web:ab286a22c0b5e54885d2a6',
    messagingSenderId: '61665813587',
    projectId: 'logintesting-dbc88',
    authDomain: 'logintesting-dbc88.firebaseapp.com',
    storageBucket: 'logintesting-dbc88.appspot.com',
    measurementId: 'G-MNP1SBGCJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIbJAkuLvJjXqI8lEqnmXdDOFNIwyULg',
    appId: '1:61665813587:android:b72d36c8e074e49b85d2a6',
    messagingSenderId: '61665813587',
    projectId: 'logintesting-dbc88',
    storageBucket: 'logintesting-dbc88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAlE-0mgkHWN5srksn9YZjE9boQT6KQg',
    appId: '1:61665813587:ios:998df801cba7f21485d2a6',
    messagingSenderId: '61665813587',
    projectId: 'logintesting-dbc88',
    storageBucket: 'logintesting-dbc88.appspot.com',
    iosClientId: '61665813587-563v9jt5durnrpjpgcs6t8imler8rh5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
