INSERT INTO tarefas (descricao, data_criacao, data_limite, finalizado) VALUES
  ('Cortar a grama', SUBDATE(NOW(), INTERVAL 28 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), FALSE),
  ('Fazer manutenção do computador', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL 11 DAY), FALSE),
  ('Organizar armário', SUBDATE(NOW(), INTERVAL 29 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), TRUE),
  ('Assistir série recomendada', SUBDATE(NOW(), INTERVAL 12 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), FALSE),
  ('Estudar para a prova de matemática', SUBDATE(NOW(), INTERVAL 9 DAY), NULL, FALSE),
  ('Responder e-mails pendentes', SUBDATE(NOW(), INTERVAL 20 DAY), NULL, FALSE),
  ('Levar o carro para revisão', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL -4 DAY), TRUE),
  ('Responder e-mails pendentes', SUBDATE(NOW(), INTERVAL 23 DAY), NULL, FALSE),
  ('Fazer meditação', SUBDATE(NOW(), INTERVAL 5 DAY), ADDDATE(NOW(), INTERVAL 0 DAY), FALSE),
  ('Organizar armário', SUBDATE(NOW(), INTERVAL 3 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), TRUE),
  ('Fazer exercício físico', SUBDATE(NOW(), INTERVAL 28 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), TRUE),
  ('Estudar linguagem de programação', SUBDATE(NOW(), INTERVAL 12 DAY), NULL, FALSE),
  ('Fazer inscrição em curso online', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), TRUE),
  ('Pagar contas do mês', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), TRUE),
  ('Fazer compras no supermercado', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL -2 DAY), FALSE),
  ('Assistir série recomendada', SUBDATE(NOW(), INTERVAL 9 DAY), NULL, FALSE),
  ('Digitalizar documentos', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 15 DAY), FALSE),
  ('Levar o carro para revisão', SUBDATE(NOW(), INTERVAL 29 DAY), ADDDATE(NOW(), INTERVAL -4 DAY), FALSE),
  ('Enviar mensagem para família', SUBDATE(NOW(), INTERVAL 23 DAY), ADDDATE(NOW(), INTERVAL 1 DAY), FALSE),
  ('Agendar corte de cabelo', SUBDATE(NOW(), INTERVAL 25 DAY), NULL, FALSE),
  ('Escrever no diário', SUBDATE(NOW(), INTERVAL 14 DAY), ADDDATE(NOW(), INTERVAL 4 DAY), FALSE),
  ('Fazer backup dos dados', SUBDATE(NOW(), INTERVAL 28 DAY), NULL, TRUE),
  ('Escrever no diário', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 7 DAY), FALSE),
  ('Assistir aula gravada', SUBDATE(NOW(), INTERVAL 15 DAY), NULL, TRUE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 8 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), TRUE),
  ('Agendar corte de cabelo', SUBDATE(NOW(), INTERVAL 13 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), TRUE),
  ('Atualizar currículo', SUBDATE(NOW(), INTERVAL 5 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), TRUE),
  ('Preparar apresentação para reunião', SUBDATE(NOW(), INTERVAL 14 DAY), ADDDATE(NOW(), INTERVAL 13 DAY), TRUE),
  ('Atualizar currículo', SUBDATE(NOW(), INTERVAL 9 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), TRUE),
  ('Digitalizar documentos', SUBDATE(NOW(), INTERVAL 16 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), FALSE),
  ('Planejar viagem de férias', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL -1 DAY), FALSE),
  ('Atualizar currículo', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 3 DAY), FALSE),
  ('Pesquisar sobre investimento', SUBDATE(NOW(), INTERVAL 23 DAY), NULL, TRUE),
  ('Fazer um bolo', SUBDATE(NOW(), INTERVAL 14 DAY), NULL, FALSE),
  ('Testar nova receita', SUBDATE(NOW(), INTERVAL 30 DAY), ADDDATE(NOW(), INTERVAL 14 DAY), TRUE),
  ('Montar móvel novo', SUBDATE(NOW(), INTERVAL 23 DAY), ADDDATE(NOW(), INTERVAL -3 DAY), TRUE),
  ('Lavar roupas', SUBDATE(NOW(), INTERVAL 26 DAY), ADDDATE(NOW(), INTERVAL -4 DAY), TRUE),
  ('Fazer inscrição em curso online', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL 7 DAY), TRUE),
  ('Atualizar lista de contatos', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL 10 DAY), FALSE),
  ('Assistir série recomendada', SUBDATE(NOW(), INTERVAL 21 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), FALSE),
  ('Revisar material do curso', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL 10 DAY), FALSE),
  ('Assistir série recomendada', SUBDATE(NOW(), INTERVAL 26 DAY), ADDDATE(NOW(), INTERVAL 3 DAY), FALSE),
  ('Fazer meditação', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), TRUE),
  ('Fazer inscrição em curso online', SUBDATE(NOW(), INTERVAL 13 DAY), ADDDATE(NOW(), INTERVAL 12 DAY), TRUE),
  ('Levar o pet ao veterinário', SUBDATE(NOW(), INTERVAL 30 DAY), ADDDATE(NOW(), INTERVAL 14 DAY), FALSE),
  ('Atualizar currículo', SUBDATE(NOW(), INTERVAL 27 DAY), ADDDATE(NOW(), INTERVAL 13 DAY), TRUE),
  ('Organizar agenda da semana', SUBDATE(NOW(), INTERVAL 27 DAY), NULL, FALSE),
  ('Levar o carro para revisão', SUBDATE(NOW(), INTERVAL 8 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), FALSE),
  ('Lavar roupas', SUBDATE(NOW(), INTERVAL 13 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), TRUE),
  ('Levar o pet ao veterinário', SUBDATE(NOW(), INTERVAL 26 DAY), ADDDATE(NOW(), INTERVAL 9 DAY), TRUE),
  ('Preparar almoço especial', SUBDATE(NOW(), INTERVAL 19 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), TRUE),
  ('Preparar almoço especial', SUBDATE(NOW(), INTERVAL 22 DAY), NULL, FALSE),
  ('Atualizar lista de contatos', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL 8 DAY), FALSE),
  ('Fazer backup dos dados', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL 14 DAY), FALSE),
  ('Fazer um bolo', SUBDATE(NOW(), INTERVAL 6 DAY), NULL, TRUE),
  ('Organizar os arquivos do computador', SUBDATE(NOW(), INTERVAL 27 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), FALSE),
  ('Atualizar currículo', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL -2 DAY), TRUE),
  ('Testar nova receita', SUBDATE(NOW(), INTERVAL 14 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), FALSE),
  ('Enviar relatório semanal', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL -3 DAY), TRUE),
  ('Limpar os vidros da janela', SUBDATE(NOW(), INTERVAL 12 DAY), ADDDATE(NOW(), INTERVAL 12 DAY), FALSE),
  ('Organizar armário', SUBDATE(NOW(), INTERVAL 4 DAY), ADDDATE(NOW(), INTERVAL 3 DAY), FALSE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL 4 DAY), TRUE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL 13 DAY), FALSE),
  ('Pagar contas do mês', SUBDATE(NOW(), INTERVAL 14 DAY), ADDDATE(NOW(), INTERVAL -1 DAY), TRUE),
  ('Montar móvel novo', SUBDATE(NOW(), INTERVAL 17 DAY), ADDDATE(NOW(), INTERVAL 0 DAY), TRUE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 18 DAY), NULL, TRUE),
  ('Levar o carro para revisão', SUBDATE(NOW(), INTERVAL 29 DAY), ADDDATE(NOW(), INTERVAL 11 DAY), FALSE),
  ('Fazer um bolo', SUBDATE(NOW(), INTERVAL 4 DAY), ADDDATE(NOW(), INTERVAL 14 DAY), TRUE),
  ('Organizar os arquivos do computador', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL 11 DAY), TRUE),
  ('Trocar lâmpadas queimadas', SUBDATE(NOW(), INTERVAL 15 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), FALSE),
  ('Levar o carro para revisão', SUBDATE(NOW(), INTERVAL 29 DAY), ADDDATE(NOW(), INTERVAL -1 DAY), FALSE),
  ('Responder e-mails pendentes', SUBDATE(NOW(), INTERVAL 12 DAY), NULL, FALSE),
  ('Organizar os arquivos do computador', SUBDATE(NOW(), INTERVAL 8 DAY), ADDDATE(NOW(), INTERVAL 2 DAY), FALSE),
  ('Consertar torneira que está vazando', SUBDATE(NOW(), INTERVAL 13 DAY), ADDDATE(NOW(), INTERVAL -1 DAY), FALSE),
  ('Fazer exercício físico', SUBDATE(NOW(), INTERVAL 5 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), FALSE),
  ('Montar plano de estudos', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 15 DAY), FALSE),
  ('Estudar para a prova de matemática', SUBDATE(NOW(), INTERVAL 4 DAY), NULL, FALSE),
  ('Lavar roupas', SUBDATE(NOW(), INTERVAL 24 DAY), ADDDATE(NOW(), INTERVAL 3 DAY), TRUE),
  ('Marcar consulta médica', SUBDATE(NOW(), INTERVAL 11 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), TRUE),
  ('Organizar agenda da semana', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL 1 DAY), FALSE),
  ('Planejar cardápio da semana', SUBDATE(NOW(), INTERVAL 7 DAY), ADDDATE(NOW(), INTERVAL 12 DAY), TRUE),
  ('Fazer manutenção do computador', SUBDATE(NOW(), INTERVAL 16 DAY), ADDDATE(NOW(), INTERVAL 4 DAY), FALSE),
  ('Enviar relatório semanal', SUBDATE(NOW(), INTERVAL 5 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), TRUE),
  ('Testar nova receita', SUBDATE(NOW(), INTERVAL 11 DAY), ADDDATE(NOW(), INTERVAL -5 DAY), FALSE),
  ('Fazer meditação', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL 10 DAY), FALSE),
  ('Fazer um bolo', SUBDATE(NOW(), INTERVAL 14 DAY), ADDDATE(NOW(), INTERVAL 8 DAY), FALSE),
  ('Enviar mensagem para família', SUBDATE(NOW(), INTERVAL 28 DAY), ADDDATE(NOW(), INTERVAL 15 DAY), TRUE),
  ('Enviar relatório semanal', SUBDATE(NOW(), INTERVAL 14 DAY), NULL, TRUE),
  ('Resolver pendências do banco', SUBDATE(NOW(), INTERVAL 21 DAY), ADDDATE(NOW(), INTERVAL 3 DAY), TRUE),
  ('Organizar agenda da semana', SUBDATE(NOW(), INTERVAL 16 DAY), ADDDATE(NOW(), INTERVAL 6 DAY), FALSE),
  ('Fazer manutenção do computador', SUBDATE(NOW(), INTERVAL 24 DAY), ADDDATE(NOW(), INTERVAL 8 DAY), FALSE),
  ('Escrever no diário', SUBDATE(NOW(), INTERVAL 5 DAY), ADDDATE(NOW(), INTERVAL -3 DAY), FALSE),
  ('Limpar os vidros da janela', SUBDATE(NOW(), INTERVAL 10 DAY), NULL, TRUE),
  ('Planejar viagem de férias', SUBDATE(NOW(), INTERVAL 22 DAY), NULL, FALSE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 24 DAY), NULL, TRUE),
  ('Organizar os arquivos do computador', SUBDATE(NOW(), INTERVAL 22 DAY), ADDDATE(NOW(), INTERVAL -4 DAY), FALSE),
  ('Limpar os vidros da janela', SUBDATE(NOW(), INTERVAL 19 DAY), ADDDATE(NOW(), INTERVAL 7 DAY), TRUE),
  ('Lavar a louça', SUBDATE(NOW(), INTERVAL 10 DAY), ADDDATE(NOW(), INTERVAL 0 DAY), TRUE),
  ('Limpar os vidros da janela', SUBDATE(NOW(), INTERVAL 18 DAY), ADDDATE(NOW(), INTERVAL 4 DAY), TRUE),
  ('Pintar a parede da sala', SUBDATE(NOW(), INTERVAL 30 DAY), ADDDATE(NOW(), INTERVAL 5 DAY), FALSE);
