version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agenda
      MYSQL_USER: joao
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

